### ISSUE TITLE
Specialized app seg fault 

### ISSUE THREAD

**Issue by Mohannadcse** [ashish-gehani/OCCAM#52]
I used OCCAM to debloat the `rm coreutil` based on the following manifest settings:
```
{ "main" : "rm.bc"
, "binary"  : "rm"
, "modules"    : []
, "native_libs" : []
, "ldflags"  : []
, "constraints"    : ["1","rm","-rf"]
, "name"    : "rm"
}
```

I receive a segmentation fault after running the specialized application. 
Here is the bitcode of the debloated application: [rm.bc.zip](https://github.com/ashish-gehani/OCCAM/files/5126784/rm.bc.zip)

**Comment by caballa** [comment]
@Mohannadcse : I tried to debug but I got stuck because the executable generated by OCCAM does not have debug symbols. Your bitcode has symbols I think. @ashish/ @ianamason  : how can I solve the lack of symbols in the executable generated by OCCAM ?

**Comment by Mohannadcse** [comment]
I don't know if this helps. This rm utility version is `rm-8.4`, if you want to download the source and build it. You can find it here [https://github.com/aspire-project/chisel-bench/tree/master/benchmark](url)

**Comment by ianamason** [comment]
Do the symbols get lost in the final link, or does one of the plethora of opt passes strip them out?
Pretty sure we could leave them in, if we knew where they were getting dropped on the floor.

**Comment by caballa** [comment]
Keep the debug symbols was easy. Just add `--no-strip` ;-)

**Comment by caballa** [comment]
@Mohannadcse : this problem should be fixed here 278770f

**Comment by Mohannadcse** [comment]
@caballa sorry for being late. I'm not quite sure if the docker machine is pulling the fixed version, but I've tested using the docker and still received seg fault error.

**Comment by caballa** [comment]
I think the version in docker hub contains the master branch which haven't been touched in a while
